server:
  port: 8081
  servlet:
    context-path: /

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

spring:
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB  # Changed to MB instead of GB for safer handling

video:
  ffprobe-path: "C:/Users/Sanjay Prajapati/Downloads/ffmpeg-7.1.1-essentials_build/ffmpeg-7.1.1-essentials_build/bin/ffprobe.exe"  # Windows example

  # Uncomment the following section only if you enable DB usage
  # datasource:
  #   url: jdbc:postgresql://localhost:5432/metadata_db
  #   username: postgres
  #   password: admin
  #   driver-class-name: org.postgresql.Driver
  # jpa:
  #   hibernate:
  #     ddl-auto: update
  #   show-sql: true
  #   properties:
  #     hibernate:
  #       dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace
